Repository 2025-KONKUK-Hackathon/FC-FRONTEND, pull requests merged in 2025-08, with the labels that each got.

#6 [setting] path alias 설정
  .gitignore
  package.json
  pnpm-lock.yaml
  tsconfig.app.json
  vite.config.ts
Labels: 🐯 지성, 🛠️ Setting

#40 [Feature] 학생회 게시글 ListItem, 일반 게시글 ListItem 공컴 생성
  src/pages/posts/list/PostList.css.ts
  src/pages/posts/list/PostList.tsx
  src/pages/posts/list/components/.gitkeep
  src/pages/posts/list/components/PostListItem.css.ts
  src/pages/posts/list/components/PostListItem.tsx
  src/pages/posts/list/components/StudentCouncilListItem.css.ts
  src/pages/posts/list/components/StudentCouncilListItem.tsx
  src/pages/posts/list/constant/.gitkeep
  src/pages/posts/list/constant/GeneralPostsDummy.ts
  src/pages/posts/list/constant/StudentCouncilPostsDummy.ts
  src/shared/components/button/Button.css.ts
  src/shared/components/category/Category.css.ts
  src/shared/constant/class.ts
  src/shared/styles/global.css.ts
  src/shared/styles/theme.css.ts
Labels: ✨Feature, 🐯 지성

#42 [Feature/#34] gathering detail
  src/assets/svg/Ic_img.svg
  src/assets/svg/ic_calendar.svg
  src/assets/svg/ic_user.svg
  src/assets/svg/ic_x.svg
  src/assets/svg/index.ts
  src/pages/gathering/detail/GatheringDetail.css.ts
  src/pages/gathering/detail/GatheringDetail.tsx
  src/pages/gathering/detail/components/.gitkeep
  src/pages/gathering/detail/components/popUp/PopUp.css.ts
  src/pages/gathering/detail/components/popUp/PopUp.tsx
  src/pages/gathering/detail/components/popUp/mockUp.ts
  src/pages/gathering/detail/constant/.gitkeep
  src/pages/gathering/detail/hooks/.gitkeep
  src/pages/gathering/detail/types/.gitkeep
  src/pages/gathering/detail/utils/.gitkeep
  src/shared/constant/subject.ts
Labels: ✨Feature, 🦊 동희

#58 [Setting/#57] axios, tanstack-query 세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/.gitkeep
  src/api/axiosInstance.ts
  src/api/constants.ts
  src/api/queryClient.ts
  src/api/request.ts
  src/api/types.ts
Labels: 🐯 지성, 🛠️ Setting

#41 [Feature/#25] gathering card 구현
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package.json
  pnpm-lock.yaml
  src/assets/svg/ic_person_grey300.svg
  src/assets/svg/ic_user.svg
  src/assets/svg/index.ts
  src/main.tsx
  src/pages/gathering/create/CreateGathering.tsx
  src/pages/gathering/detail/GatheringDetail.css.ts
  src/pages/gathering/detail/GatheringDetail.tsx
  src/pages/gathering/members/ApplicantList.tsx
  src/pages/posts/create/CreatePost.tsx
  src/pages/posts/detail/PostDetail.tsx
  src/router/Layout.tsx
  src/router/constant/Routes.ts
  src/shared/components/gatheringCard/GatheringCard.css.ts
  src/shared/components/gatheringCard/GatheringCard.tsx
  src/shared/components/gatheringCard/component/StatusChip.css.ts
  src/shared/components/gatheringCard/component/StatusChip.tsx
  src/shared/components/nonFound/NonFound.tsx
  src/shared/constant/.gitkeep
  src/shared/constant/class.ts
  src/shared/constant/status.ts
  src/shared/styles/global.css.ts
  src/shared/styles/layers.css.ts
  src/shared/styles/reset.css.ts
  src/shared/styles/theme.css.ts
  tsconfig.json
  vercel.json
  vite.config.ts
Labels: ✨Feature, 🦁 규운

#63 [Feature/#60] gather detail api
  src/api/types.ts
  src/assets/svg/ic_chevron_left.svg
  src/pages/gathering/detail/GatheringDetail.css.ts
  src/pages/gathering/detail/GatheringDetail.tsx
  src/pages/gathering/detail/components/popUp/PopUp.css.ts
  src/pages/gathering/detail/components/popUp/PopUp.tsx
  src/pages/gathering/detail/components/popUp/mockUp.ts
  src/pages/gathering/detail/hooks/index.ts
  src/pages/gathering/detail/hooks/useGatheringDetail.ts
  src/pages/gathering/detail/hooks/useGatheringMutations.ts
  src/pages/gathering/detail/types/Gathering.ts
  src/pages/mainLayout/MainLayout.css.ts
  src/pages/mainLayout/MainLayout.tsx
  src/router/Layout.tsx
  src/shared/components/Footer/Footer.css.ts
  src/shared/components/Header/Header.css.ts
  src/shared/components/gatheringCard/GatheringCard.tsx
  src/shared/components/gatheringCard/component/StatusChip.tsx
  src/shared/constant/queryKey.ts
  src/shared/constant/status.ts
  src/shared/styles/global.css.ts
Labels: ✨Feature, 🦊 동희

#51 [Feature/#45] gathering create 페이지
  package.json
  pnpm-lock.yaml
  src/assets/svg/index.ts
  src/pages/gathering/create/CreateGathering.css.ts
  src/pages/gathering/create/CreateGathering.tsx
  src/pages/gathering/create/hooks/.gitkeep
  src/pages/gathering/create/hooks/useGatheringForm.ts
  src/shared/components/formSection/FormSection.css.ts
  src/shared/components/formSection/FormSection.tsx
  src/shared/components/input/Input.css.ts
  src/shared/components/input/Input.tsx
  src/shared/constant/class.ts
Labels: ✨Feature, 🦁 규운

#71 [Feature/#68] login api
  src/pages/auth/login/Login.css.ts
  src/pages/auth/login/Login.tsx
  src/pages/auth/login/components/.gitkeep
  src/pages/auth/login/constant/.gitkeep
  src/pages/auth/login/hooks/useLogin.ts
  src/pages/auth/login/hooks/useLoginForm.ts
  src/pages/auth/login/types/.gitkeep
  src/pages/auth/login/utils/.gitkeep
Labels: ✨Feature, 🐣 정현

#72 [Feature/#69] signup api
  src/pages/auth/signup/Signup.css.ts
  src/pages/auth/signup/Signup.tsx
  src/pages/auth/signup/components/SignupForm.css.ts
  src/pages/auth/signup/components/SignupForm.tsx
  src/pages/auth/signup/constant/.gitkeep
  src/pages/auth/signup/hooks/useSignupForm.ts
  src/pages/auth/signup/hooks/useSignupMutations.ts
  src/pages/auth/signup/types/signupTypes.ts
  src/pages/auth/signup/utils/.gitkeep
Labels: ✨Feature, 🐣 정현

#80 [Style/#76] 로고 및 마이페이지 스탬프 로직 변경
  src/assets/svg/ic_logo.svg
  src/assets/svg/index.ts
  src/pages/user/User.tsx
  src/pages/user/types/info.ts
  src/shared/components/Footer/Footer.css.ts
  src/shared/components/Footer/Footer.tsx
  src/shared/components/Header/Header.css.ts
  src/shared/components/Header/Header.tsx
  src/shared/components/dropDown/DropDown.css.ts
Labels: 🎨 Style, 🦊 동희

#83 [Feature/#81] 인증번호 api request body -> query 수정
  src/pages/auth/signup/hooks/useSignupMutations.ts
Labels: ✨Feature, 🐣 정현

#86 [Feat/#84] 게시판 목록, routing 수정
  src/assets/svg/ic_chevron_down.svg
  src/assets/svg/ic_chevron_up.svg
  src/assets/svg/index.ts
  src/pages/auth/login/Login.css.ts
  src/pages/auth/login/Login.tsx
  src/pages/posts/list/PostList.css.ts
  src/pages/posts/list/PostList.tsx
  src/pages/posts/list/components/StudentCouncilListItem.tsx
  src/pages/posts/list/types/postList.ts
  src/router/ProtectedRoute.tsx
  src/router/Router.tsx
  src/shared/components/dropDown/DropDown.css.ts
  src/shared/components/dropDown/DropDown.tsx
  src/shared/components/postCard/PostCard.tsx
Labels: ✨Feature, 🦊 동희

#89 [Feat/#87] info page
  src/pages/info/Info.css.ts
  src/pages/info/Info.tsx
  src/pages/info/components/Link.css.ts
  src/pages/info/components/Link.tsx
  src/router/Router.tsx
  src/router/constant/Routes.ts
Labels: ✨Feature, 🦊 동희

#90 [Feature/#81] 모임 탭 다양한 추가기능
  src/pages/gathering/list/GatheringList.css.ts
  src/pages/gathering/list/GatheringList.tsx
  src/pages/gathering/list/constant/FilterOptions.ts
  src/pages/gathering/list/hooks/.gitkeep
  src/pages/gathering/list/hooks/useGatheringList.ts
  src/pages/gathering/list/types/.gitkeep
  src/pages/gathering/list/types/gatheringList.ts
  src/pages/user/User.tsx
  src/pages/user/types/info.ts
  src/shared/components/button/createPost/CreatePostButton.tsx
  src/shared/components/gatheringCard/GatheringCard.css.ts
  src/shared/components/gatheringCard/GatheringCard.tsx
  src/shared/components/gatheringCard/component/StatusChip.css.ts
  src/shared/styles/global.css.ts
Labels: ✨Feature, 🐯 지성

#93 [Style/#91] 스타일 수정
  src/assets/svg/ic_link.svg
  src/assets/svg/index.ts
  src/pages/gathering/list/GatheringList.css.ts
  src/pages/gathering/list/GatheringList.tsx
  src/pages/info/Info.css.ts
  src/pages/info/Info.tsx
  src/pages/posts/list/PostList.tsx
  src/pages/user/User.css.ts
  src/pages/user/User.tsx
  src/pages/user/mockup.ts
  src/pages/user/types/info.ts
  src/router/Router.tsx
  src/router/constant/Routes.ts
  src/shared/components/Footer/Footer.tsx
  src/shared/components/postCard/PostCard.tsx
Labels: 🎨 Style, 🦊 동희

#95 [Feature/#92] image S3 게시
  src/pages/gathering/create/CreateGathering.tsx
  src/pages/gathering/create/hooks/useGatherCreateMutations.ts
  src/pages/gathering/create/hooks/useGatheringForm.ts
  src/pages/posts/create/hooks/usePostsCreateMutation.ts
  src/pages/posts/create/hooks/usePostsForm.ts
  src/shared/utils/removeQueryString.ts
Labels: ✨Feature, 🦁 규운

#104 [Fix/#103] 전체적 스타일 변경
  src/pages/gathering/detail/GatheringDetail.css.ts
  src/pages/gathering/detail/GatheringDetail.tsx
  src/pages/gathering/detail/components/popUp/PopUp.tsx
  src/pages/gathering/list/GatheringList.tsx
Labels: 🔨 Fix, 🦊 동희

#106 [Fix/#100] 다양한 수정사항 2
  src/App.tsx
  src/pages/gathering/list/GatheringList.css.ts
  src/pages/posts/create/CreatePost.tsx
  src/pages/posts/create/hooks/usePostsForm.ts
  src/pages/posts/create/types/PostsCreate.ts
  src/pages/posts/detail/PostDetail.tsx
  src/pages/posts/detail/hooks/usePostDetail.ts
  src/pages/posts/detail/hooks/usePostMutations.ts
  src/pages/posts/list/PostList.css.ts
  src/pages/posts/list/PostList.tsx
  src/pages/user/User.css.ts
  src/pages/user/User.tsx
  src/pages/user/constant/stamp.ts
  src/shared/components/Footer/Footer.tsx
  src/shared/components/confirmModal/ConfirmModal.css.ts
  src/shared/components/confirmModal/ConfirmModal.tsx
  src/shared/components/gatheringCard/GatheringCard.css.ts
  src/shared/components/toast/Toast.css.ts
  src/shared/components/toast/Toast.tsx
  src/shared/components/toast/useToast.tsx
  src/shared/types/toast.ts
  src/shared/utils/errorHandler.ts
  src/shared/utils/timeUtils.ts
Labels: 🔨 Fix, 🐯 지성

#108 [Fix/#107] QA 수정사항 반영
  src/pages/gathering/detail/GatheringDetail.css.ts
  src/pages/gathering/list/GatheringList.css.ts
  src/pages/posts/detail/PostDetail.css.ts
  src/pages/posts/list/components/StudentCouncilListItem.css.ts
Labels: 🔨 Fix, 🐯 지성
